name:

on:
  push:


jobs:
  linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - run: ./linux/build_installer.sh
      name: Build installer

    - run: sudo apt-get install -y xvfb x11-utils libqt5gui5
      name: Install GUI testing libraries
    - run: tar xvf ./linux/angr-management-installer-linux.tar.gz
      name: Extract installer
    - run: ./angr-management-install/install.sh
      name: Run installer
    - run: |
        xvfb-run ~/.angr-management/python/install/bin/angr-management &
        sleep 10 && output=$(DISPLAY=:99 xwininfo -tree -root)
        [[ "$output" == *"angr management"* ]] || exit 1
        exit 0
      name: Test angr management start
